### ISSUE TITLE
[Task-2] - Render a dummy cards

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#2]
All the recipes will be wrapped in a row. We can decide how many recipes will fit inside the row before they wrap and that on different page sizes using the [row-columns functionality from bootstraps grid](https://getbootstrap.com/docs/4.4/layout/grid/#row-columns).

For this task, we will add 4 cards to the `DOM` inside 1 row.

**Task:**
- [x] Firstly, let's contain the application, add a wrapper around the description with the class `container`. All our code will be rendered inside this container with the exception of the navbar.
  https://getbootstrap.com/docs/4.4/layout/overview/#containers
- [x] Add a row to wrap the columns https://getbootstrap.com/docs/4.4/layout/grid/
- [x] Add 4 columns with the class `col-sm-6`. This will allow from small screens and upwards to have 2 columns. (12/6 = 2)
  https://getbootstrap.com/docs/4.4/layout/grid/#stacked-to-horizontal
- [x] Add the following HTML in each `col` to represent [a card](https://getbootstrap.com/docs/4.4/components/card/).
  ```html
  <div className="card">
    <img src="..." className="card-img-top" alt="..." />
    <div className="card-body">
      <h5 className="card-title">Card title</h5>
      <p className="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    </div>
  </div>
  ```
- [x] Add a margin on the bottom with the size `4` of each `col` to prevent the cards from touching each other wile stacking.
https://getbootstrap.com/docs/4.0/utilities/spacing/
- [x] Figure out a way with bootstrap classes to have only 1 column for `xs` display, 2 columns from `sm` to `lg` displays and 3 columns from `lg` displays and above.
https://getbootstrap.com/docs/4.0/layout/grid/#grid-options
https://getbootstrap.com/docs/4.0/layout/grid/#mix-and-match

**Outcome:**
- **`xs` display**
  <img width="300" alt="Screenshot 2020-06-02 at 23 29 06" src="https://user-images.githubusercontent.com/7160913/83576098-e9eb2c80-a528-11ea-969b-a9a2b5be3df8.png">

- **`sm` to `lg` displays**
<img width="758" alt="Screenshot 2020-06-02 at 23 28 54" src="https://user-images.githubusercontent.com/7160913/83576179-1010cc80-a529-11ea-8faa-3dd07b42f0ac.png">

- **`lg` displays and above**
<img width="1043" alt="Screenshot 2020-06-02 at 23 28 45" src="https://user-images.githubusercontent.com/7160913/83576217-23bc3300-a529-11ea-8cf9-3ce25982afb2.png">
