### ISSUE TITLE
[Task-14] - Add filter links to the homepage

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#27]

**Comment by samdemaeyer** [comment]
Let's add categories to the application. 

**Task:**
- [ ] Underneath the main text, add a `row` with a margin on the bottom of `4`
- [ ] Inside the row add 5 links with the following styling:
  - [ ] Margin on the bottom of `1`
  - [ ] Uppercased 
  - [ ] Border on the bottom of `1px` 
  - [ ] Styled as an `h6` tag
  - [ ] Text of the links: **Speedy, Slow, Side, Small, Sweet**
- [ ] Each link should link to the same page, but with a `queryParam` => `category={category}`
  eg. `?category=sweet`
- [ ] When I click on the link again, the traget will be to remove the `queryParam`
  eg. The link **Sweet** should link to `http://localhost:3000/?category=sweet`. Once the `queryParam` is added to the browser, the link **Sweet** should point at `http://localhost:3000`
