### ISSUE TITLE
[Task-16] - Add a filter input field

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#29]
Now we can filter on categories, let's go ahead and add a search field.

**Task:**
- [ ] Add a search field below the links. (Add a margin on the of `4`) 
- [ ] Make sure the search field is styled as bootstrap input field and add padding left and right of `4`
  - [ ] Add a placeholder `Search recipes...`
- [ ] Link up the value of the input field with a new `queryParam` called `search`.

**Outcome:**
![Screenshot 2020-06-22 at 19 57 02](https://user-images.githubusercontent.com/7160913/85324977-bf0a4d80-b4c2-11ea-9065-c3a8da9adf0b.png)
