### ISSUE TITLE
[Task-3] - Fetch all recipes

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#3]
The project includes some JSON files that can be fetched via the localhost. Don't worry, it sounds scarier than it is. In this ticket, we will fetch all the recipes and log them in the console.

**Task:**
- [x] Convert the file to a class-based component.
- [x] Using the `componentDidMount` hook, let's fetch the data from the JSON files. 
  - You can use this URL: `/api/recipes/all.json`
  https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
- [x] Store the data in the `state` under the key `recipes`.
- [x] In the `render` hook, log all recipes in the console.

**Outcome:**
<img width="712" alt="Screenshot 2020-06-02 at 23 45 24" src="https://user-images.githubusercontent.com/7160913/83577065-26b82300-a52b-11ea-9dfa-c449af5b897d.png">
