### ISSUE TITLE
[Task-4] - Display the recipes in the cards

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#4]
Now we have all recipes stored in the state, let's loop through all of them and populate the cards with the content of each recipe.

**Task:**
- [x] Instead of having 4 dummy cards, loop through all recipes stored in the `state` and render a dummy card for each one.
<img width="400" alt="Screenshot 2020-06-02 at 23 49 55" src="https://user-images.githubusercontent.com/7160913/83577312-c675b100-a52b-11ea-93bb-55a4f3dea6d3.png">

- [x] Replace the dummy content with the actual content from the recipes.  
  - Image (the `alt` can be the title of the recipe)
  - Title
  - Description

- [ ] Make sure all recipe cards are the same height.

**Outcome:**
<img width="975" alt="Screenshot 2020-06-02 at 23 53 09" src="https://user-images.githubusercontent.com/7160913/83577509-3e43db80-a52c-11ea-9b70-b249d8f6a9f0.png">
