### ISSUE TITLE
[Task-5] - Add a router

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#5]
As we will have multiple pages, we will need a router to handle this. In this task, we will install a router, and move the content inside the `container` to a separate component.

**Task:**
- [x] Install the react web router (https://reacttraining.com/react-router/web/guides/quick-start)
- [x] Create a new component and move all the content that is currently inside the `container`
- [x] Render the new component instead.
