### ISSUE TITLE
[Task-7] - Fetch a single recipe

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#7]
As we now have access to the ID that the page is scoped by, we can now also fetch the data for that single record. The reason for doing another fetch at this point is because we will receive more data than in the `all.json` endpoint.

**Task:**
- [x] Using the `componentDidMount` hook, let's fetch the data from the JSON file.
  - The URL for this data will be: `/api/recipes/[ID].json` where **`[ID]`** is the actual ID
  eg. `/api/recipes/1.json`
- [x] Store the response data in the state.
- [x] Display the following details from the recipe:
  - [x] **Title** (`<h2>`, uppercased, centered, the secondary color, margin on the bottom of `4`)
  - [x] **Description** (`<p>`, centered)
  - [x] **Image** (the image should now come from the nested object called `recipeDetail`, centered)
  - [x] **Detail description** (`<div>`, 1px border at the bottom, padding on the bottom of `4`)
  _The detail description should also come from the nested object called `recipeDetail`_

**Outcome:**
<img width="905" alt="Screenshot 2020-06-03 at 00 56 29" src="https://user-images.githubusercontent.com/7160913/83580872-15741400-a535-11ea-931f-1854a76b6cc6.png">
