### ISSUE TITLE
[Task-9] - Render the ingredients and preparation steps

### ISSUE THREAD

**Issue by samdemaeyer** [KiraSl/react-recipes#9]
As you will have noticed, in the payload for each recipe, we have more info than what we are displaying currently. Let's go ahead and display the following info on the page.
- **Title**
- **Serves**
- **Ingredients**
- **Preparation steps**

**Task:**
Underneath the **recipe detail description**, let's render the title again. 
Beneath the title, let's render a `row` with 2 cols `.col-md-4` & `.col-md-8`. 
In the first `col`, render the serves and the ingredients, in the second `col` render the preparation steps.
- [x] **Title** (`<h6>`, secondary color, uppercase with a margin on the **top AND bottom** of `4`)
- [x] **Serves** (`<p>`, _italic_, structured like this: `Serves [#SERVES]` where **[#SERVES]** is the nr of serves provided by the API)
- [x] **Ingredients** (for each ingredient: `<li>`, **bold**, no bullet point, and no indentation)
- [x] **Preparation steps** (for each step: `<p>`)

**Outcome:**
![Screenshot 2020-06-03 at 11 51 29](https://user-images.githubusercontent.com/7160913/83628547-94e30100-a590-11ea-920e-b000e3ac5e11.png)
